---
name: demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and test Celesta demo
        run: mvn verify
        working-directory: java-maven
