---
name: slides

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven      
      - name: Set up dot
        run: sudo apt-get install -y graphvi
      - name: Build with Maven
        run: mvn clean verify
        working-directory: slides
      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: slides/target/generated-slides
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
